### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk

# Check what platform we're on.
case "$OSTYPE" in
    "darwin"*) os="macOS";;
    "linux-gnu") os="Linux";;
    *) os="Unknown";;
esac

# Nicer ls.
case "$os" in
    "macOS") alias ls="gls -h --color=auto --group-directories-first --ignore $'Icon\r'";;
    "Linux") alias ls="ls -h --color=auto --group-directories-first";;
esac

# Auto ls after cd.
function chpwd() {
    emulate -L zsh; ls
}

# Load cargo environment.
source ${HOME}/.cargo/env

# Load zsh-vi-mode plugin.
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode

# Start starship prompt.
eval "$(starship init zsh)"
